### ISSUE TITLE
Why is multivariate Gaussian distribution noise used to directly add to the ground truth for the generation of evaluation trajectory

### ISSUE THREAD

**Issue by wsp666** [Samleo8/RadarSLAMPy#12]

**Comment by wsp666** [comment]
In trajectoryPlotting code, the generation of evaluation trajectory is the sum of ground truth and Gaussian noise.

**Comment by atomicapple0** [comment]
In `trajectoryPlotting.py`, the code within the `if __name__ == "__main__":` block is purely for testing the methods in that file. 

We created a dummy eval trajectory and plotted it with the ground truth to check that we are correctly opening, parsing, and plotting the dataset.
